[phases]
build = [
  "composer install --optimize-autoloader --no-dev"
]

start = [
  "php artisan key:generate",
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan serve --host=0.0.0.0 --port=${PORT}"
]

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "http://your-app-url.com"

[env]
PHP_VERSION = "8.1"
NODE_VERSION = "18"
